### ISSUE TITLE
Release missing

### ISSUE THREAD

**Issue by berlincount** [dmacvicar/ruby-rpm-ffi#12]
Hello,

https://rubygems.org/gems/rpm is still providing release 0.0.4, which lacks support for e.g. CentOS 7

please do a release, and upload it :)

Cheers,

   count

**Comment by dmacvicar** [comment]
No problem. Can you tell me in which way the current master adds support for CentOS 7?

**Comment by berlincount** [comment]
librpm.so.3 ;)

**Comment by dmacvicar** [comment]
Done!

**Comment by berlincount** [comment]
Cheers :) using the new release instead of a git ref in our code now.
